### PR TITLE
Marketplace Conformance

### LINKED ISSUE #60: FireFox Plugin Failed Review
The plugin was disabled in the Firefox marketplace for the following reason:

```
This add-on didn&#x27;t pass review because of the following problems:

1) This extension uses a registered trademark of Mozilla in its name or icon and is unallowable under Mozilla’s Trademark Policy (https://www.mozilla.org/foundation/trademarks/policy/).
For Mozilla trademarks, the usage of “Mozilla” and “Firefox” are generally not allowed in the add-on name, except in the following format: “ADD-ON NAME for Firefox.”
icon32.png
about-logo.png
firefox-wordmark.svg
```

### PR DESCRIPTION
**Pull request by Unthrottled**
#### Description

- Removed all Firefox trademarks from the plugin, save for `Doki Theme for Firefox` which is allowed.
- Themed the Doki logo in the popup, tab, & favicon to the current selected theme.

#### Motivation and Context

- Closes #60 

#### Screenshots (if appropriate):

image

#### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [X] I updated the version (base package.json and re-built the master extension). // waiting for #63 
- [X] I updated the changelog with the new functionality.

### CODE REVIEW

File: firefoxThemes/popup/popup.js [hunk 1]
```diff
@@ -1,3 +1,66 @@
...
+    canvas.width = options.width;
+    canvas.height = options.height;
+    const canvasCtx = canvas.getContext('2d');
+    canvasCtx.drawImage(svgImage, 0, 0);
+    const imgData = canvas.toDataURL('image/png');
+    callback(imgData);
+    try {
+      document.body.removeChild(svgImage)
+    } catch (e) {
+    }
```
Comment (ZimCodes) [inline firefoxThemes/popup/popup.js:47]: Instead of using a `try/catch` block, [```Element.remove()```](https://developer.mozilla.org/en-US/docs/Web/API/Element/remove) can be used instead.

File: firefoxThemes/popup/popup.js [hunk 2]
```diff
@@ -20,15 +84,16 @@ const backgroundTypes = {
 /*Set color of popup menu based on theme*/
 function setCSS(chosenTheme) {
   if (!chosenTheme) return;
-  const {colors, information} = chosenTheme.definition;
-  root.style.setProperty('--switch-shadow-color',information.dark ? 'white' : 'black');
-  root.style.setProperty('--doki-shadow',information.dark ? '11px #fff' : '11px #000');
+  themeDokiLogo(chosenTheme);
+  const {colors} = chosenTheme.definition;
+  root.style.setProperty('--switch-shadow-color',colors.accentColor);
+  root.style.setProperty('--doki-shadow', `11px ${colors.accentColor}`);
```
Comment (ZimCodes) [inline firefoxThemes/popup/popup.js:90]: `11px` effect can be placed in *popup.css* as it's a constant value.

File: firefoxThemes/waifus/tab.js [hunk 3]
```diff
@@ -1,3 +1,65 @@
...
+    canvas.width = svgImage.clientWidth;
+    canvas.height = svgImage.clientHeight;
+    const canvasCtx = canvas.getContext('2d');
+    canvasCtx.drawImage(svgImage, 0, 0);
+    const imgData = canvas.toDataURL('image/png');
+    callback(imgData);
+    try {
+      document.body.removeChild(svgImage)
+    } catch (e) {
+    }
```
Comment (ZimCodes) [inline firefoxThemes/waifus/tab.js:46]: Another `try/catch` block to be replaced with `Element.remove()`.

File: firefoxThemes/waifus/tab.js [hunk 4]
```diff
@@ -24,16 +86,60 @@ function keyConfirm(e) {
...
+      root.style.setProperty('--base-background-color', currentTheme.definition.colors.baseBackground);
+
       if (storage.showWidget === undefined || storage.showWidget) {
         document.querySelector("body").innerHTML =
           `
     <main>
     <div class="logo-and-wordmark">
         <div class="logo"></div>
-        <div class="wordmark"></div>
+        <div class="wordmark">Doki Theme for Firefox</div>
```
Comment (ZimCodes) [inline firefoxThemes/waifus/tab.js:142]: The title for this on the homepage is quite long. It would be better to reduce the title to simply **Doki Theme** as we already know the platform this extension is used for.

**Review by ZimCodes — CHANGES_REQUESTED** [review]
Using bit-wise operations for color changes? Nice. I was thinking about how to change the color of the logo in the popup menu without using `filter`. 

In any case, these are the feedback to be reviewed before merging.

**Review by ZimCodes — DISMISSED** [review]
Alright, looks good! These changes are ready for the marketplace.

File: firefoxThemes/modules/logo.js [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+  const url = getSvgUrl(svg);
+  svgUrlToPng(url, options, (imgData) => {
+    callback(imgData);
+    URL.revokeObjectURL(url);
+  });
+};
+
+/*Update the browser action logo to match current theme color*/
+function updateBrowserLogo(ctxCanvas, image) {
+  let width = image.width === 60 ? 74: image.width;
```
Comment (ZimCodes) [inline firefoxThemes/modules/logo.js:61]: Fixes the browser action logo expanding in the toolbar when clicked

**Review by ZimCodes — APPROVED** [review]

File: firefoxThemes/modules/logo.js (hunk 5 above)
Comment (ZimCodes) [reply firefoxThemes/modules/logo.js:61]: https://user-images.githubusercontent.com/23222943/132791858-c5a8d27a-9a5c-429b-940e-82ffd05cd70e.mp4

**Comment by Unthrottled** [comment]
Things left todo:

- [ ] Kanna's secondary sticker omitted
- [ ] Mixed Mode Themed Favicon Works

**Comment by Unthrottled** [comment]
@ZimCodes I appreciate the enthusiasm on pushing up changes. Let's try to keep things collaborative, please. We haven't worked together enough, for me to get a feel for what you might expect code to look like. 

I already know that you care more than me about some various code structure, conventions, n' stuff. Most of the stuff that you did was aight, let's just not get out of hand with lone ranger-ing stuff. 

That being said, I am currently dragging my feet on getting this merged because I am trying to get my 2 new themes out the door, so that way when I resubmit, I'll have my new themes.

If you wanted to take a look at the Mixed mode favicon issue or finding a way to put modules into the background scripts (or maybe re thinking the browser extension icon theming trigger, because it was not changing colors in mixed mode when the empty active tab changed), that'd be cool.

File: firefoxThemes/modules/contentConfig.js [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+      break;
+    default:
+      break;
+  }
+  return scripts.map(script => {
+    return {file: `${baseURL}${script}`};
+  });
+}
+
+export {updateOptions};
```
Comment (ZimCodes) [inline firefoxThemes/modules/contentConfig.js:68]: *Content Script* module. Handles everything relating to registering and unregistering *Content Scripts*

File: firefoxThemes/modules/modes/mix.js [hunk 7]
```diff
@@ -0,0 +1,140 @@
...
+              browser.storage.local.set({currentThemeId, mixedTabs: storage.mixedTabs});
+            }
+            //Initialize first (and only) new tab with the default theme
+            loadTheme(themes, currentThemeId);
+          }
+        });
+    });
+}
+
+export {setupMixedUpdate, mixTabCleanup};
```
Comment (ZimCodes) [inline firefoxThemes/modules/modes/mix.js:140]: *Mix Mode* module. Things pertaining to the functionality of *Mixed mode*.

File: firefoxThemes/modules/modes/normal.js [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+            browser.storage.local.set({currentThemeId: undefined});
+            browser.theme.reset();
+          } else {
+            loadTheme(themes, msg.currentThemeId);
+          }
+        });
+    });
+}
+
+export {normalUpdate};
```
Comment (ZimCodes) [inline firefoxThemes/modules/modes/normal.js:43]: **Normal Mode** module. Handles functionality of both random and user selected themes. Random is included here because the selection of a random theme occurs in`popup.js`. That theme then gets sent here to be loaded like a user selected theme.

File: firefoxThemes/modules/utils/browser.js [hunk 9]
```diff
@@ -0,0 +1,14 @@
...
+
+/*Reload all tabs based on filter*/
+async function reloadTabs(obj) {
+  const tabs = await browser.tabs.query(obj);
+  for await(const tab of tabs) {
+    browser.tabs.reload(tab.id);
+  }
+}
+
+export {optionsPage,reloadTabs};
```
Comment (ZimCodes) [inline firefoxThemes/modules/utils/browser.js:14]: Custom browser extension functions.

File: firefoxThemes/modules/utils/random.js [hunk 10]
```diff
@@ -0,0 +1,12 @@
...
+  themes = Object.keys(themes);
+  let randNum = getRandomNumber(0, themes.length);
+  return themes[randNum];
+}
+
+/*Retrieves a random number from min(inclusive) to max(exclusive)*/
+function getRandomNumber(min, max) {
+  return Math.floor(Math.random() * (max - min)) + min;
+}
+export {getRandomThemeId};
```
Comment (ZimCodes) [inline firefoxThemes/modules/utils/random.js:12]: Random utilities.

File: firefoxThemes/modules/utils/states.js [hunk 11]
```diff
@@ -0,0 +1,12 @@
...
+  NONE: 0,
+  INITIAL: 1,
+  RESET: 2
+};
+/*Enums for background types*/
+const backgroundTypes = {
+  PRIMARY: 0,
+  SECONDARY: 1
+};
+export {mixedStates,backgroundTypes};
```
Comment (ZimCodes) [inline firefoxThemes/modules/utils/states.js:12]: Enums/States module.

File: firefoxThemes/waifus/faviconLoader.js [hunk 12]
```diff
@@ -0,0 +1,25 @@
+import {buildSVG, svgToPng} from "../modules/utils/themes/logo.js";
+
+function setThemedFavicon(currentTheme) {
```
Comment (ZimCodes) [inline firefoxThemes/waifus/faviconLoader.js:3]: The functions handling the favicon theming is located here!

Comment (ZimCodes) [reply firefoxThemes/waifus/faviconLoader.js:3]: For the most part, the *Mixed Mode* favicon theming is live! 

## Issue
Except, if I try to **create a series of new tabs at the speed of light**, then the default favicon will be displayed for now onwards.

- [ ] Fix default favicon displaying after creating new tabs quickly

File: firefoxThemes/waifus/index.html [hunk 13]
```diff
@@ -11,6 +11,8 @@
     <script type="module" src="tab.js" defer></script>
     <!--Adds/Removes Waifu-->
     <script src="waifu.js" defer></script>
+  <!--Load Themed Favicon-->
+  <script type="module" src="faviconLoader.js" defer></script>
```
Comment (ZimCodes) [inline firefoxThemes/waifus/index.html:15]: Separated favicon theming to a separate file for modularity *and easy testing*.

Can switch out `defer` here for `async` to change the favicon theme lazily. *Preferred*

File: firefoxThemes/DokiThemeDefinitions.js [hunk 14]
```diff
@@ -1 +1 @@
...
...424","diff.inserted":"#223B28","diff.modified":"#253F4C","caretRow":"#313a49","baseIconColor":"#6c747d","contrastColor":"#404a57","nonProjectFileScopeColor":"#33393c","secondaryBackground":"#2c3039","selectionForeground":"#fbfbfb","headerColor":"#2e343e","baseBackground":"#323742","borderColor":"#393e48","buttonColor":"#3a4148","selectionInactive":"#403545","identifierHighlight":"#373c47","selectionBackground":"#4f3a4e","selectionBackgroundTransparent":"#4f3a4eAA","buttonFont":"#ada89c","foregroundColor":"#b0b0b0","highlightColor":"#3d4754","disabledColor":"#5b606f","accentColorTransparent":"#6688ad5A","accentColorLessTransparent":"#6688ad9A","accentColorMoreTransparent":"#6688ad2A","accentColor":"#6688ad","accentContrastColor":"#182f42","infoForeground":"#b0a17f","startColor":"#595959","stopColor":"#e66895","testScopeColor":"#2e3a3c","popupMask":"#928d8d05","codeBlock":"#3c3443","foldedTextBackground":"#323743","textEditorBackground":"#2b303b","editorAccentColor":"#8bd9ff","classNameColor":"#89acf6","htmlTagColor":"#6c7c96","stringColor":"#F6E9CB","keyColor":"#61ead9","keywordColor":"#ea73d6"},"overrides":{"theme":{"colors":{},"properties":{"ntp_background_alignment":"right"}}}}};
```
Comment (ZimCodes) [inline firefoxThemes/DokiThemeDefinitions.js:1]: Added a `export` keyword here in order to take advantage of JavaScripts modules. *And to `import` DokiThemeDefinitions into the `resource.js` background script.*

**Review by ZimCodes — COMMENTED** [review]
> If you wanted to take a look at the Mixed mode favicon issue or finding a way to put modules into the background scripts (or maybe re thinking the browser extension icon theming trigger, because it was not changing colors in mixed mode when the empty active tab changed), that'd be cool.

All suggested modifications have been address, especially the 
> put modules into the background scripts

part. 
## Code Summary:
- Fix *Mixed mode* favicon issue except with a new issue.
- Refactor code into modules.
- Starting *Mix mode* for the first time now changes the popup menu to the correct theme instead of staying the default.

**Comment by ZimCodes** [comment]
> Let's try to keep things collaborative, please.

> I already know that you care more than me about some various code structure, conventions, n' stuff. Most of the stuff that you did was aight, let's just not get out of hand with lone ranger-ing stuff.

Nah, I don't know a lot about standards and stuff, I just learn them as I go. I try to make the code written as easier to manage for collaboration and for the future self *(those who view this again sometime in the future)*. But rest assured, I'm not going to go too crazy with the lone wolfing.

> I am trying to get my 2 new themes out the door, so that way when I resubmit, I'll have my new themes.

Understood! Sounds like a plan!

File: firefoxThemes/DokiThemeDefinitions.js (hunk 14 above)
Comment (Unthrottled) [reply firefoxThemes/DokiThemeDefinitions.js]: Just as a heads up, I might remove this file from version control in the future.

File: firefoxThemes/waifus/faviconLoader.js (hunk 12 above)
Comment (Unthrottled) [reply firefoxThemes/waifus/faviconLoader.js:3]: :laughing: I just held down ctrl-t and was able to verify the issue. 
I'll just spin up a new issue once this is merged to address this. As this is probably not what users are normally going to do.

**Comment by Unthrottled** [comment]
@ZimCodes Thanks for getting the favicon stuff cleaned up for me, I appreciate it!

I've updated the build process to omit Kanna's duplicate asset. I might spend some time later in the future, into making the build script less scary.

I also included an update to the build script that adds the `export` to the DokiThemeDefinitions.js 

I'm going to merge this in, and get the new themes taken care of, then I submit the plugin for re-approval.

File: firefoxThemes/DokiThemeDefinitions.js (hunk 14 above)
Comment (ZimCodes) [reply firefoxThemes/DokiThemeDefinitions.js]: Will *DokiThemeDefinitions* be hosted on a server and get retrieved from there? If so, then a service worker system will have to be established. *This will probably fit nicely with the new [Firefox Manifest V3](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/)*

> Background pages will be replaced by background service workers 

I'll say wait on adding service workers though until this is officially released.

Comment (Unthrottled) [reply firefoxThemes/DokiThemeDefinitions.js]: > Will DokiThemeDefinitions be hosted on a server and get retrieved from there?

It will still be bundled with the extension itself. Since it is an automatically generated file, there really is not a point for it to hang out in version control. I'll probably do that when I refactor the build script to be more comprehensible.
